export const GET_WEATHER_REPORT = "GET_WEATHER_REPORT";
export const WEATHER_REPORT_RECIEVED = "WEATHER_REPORT_RECIEVED";

export const GET_CITIES = "GET_CITIES";
export const CITIES_RECIEVED = "CITIES_RECIEVED";
